### ISSUE TITLE
Задача 11. Исходные данные: Отчет «Звонки». Скорректировать типовой отчет «Звонки»: удалить группировку по ответственному; добавить поля «Врач», «Специализация», «Статус» из документа Заявка, где вид события = исходящий звонок; переименовать поле «Ответственный» на «Оператор». Оценка: 21 балл.

### ISSUE THREAD

**Issue by TanyaAnferova** [nmivan/learning#1]
1. Удалить группировку по ответственному.
![1](https://user-images.githubusercontent.com/52575191/77723173-879a1b00-7011-11ea-9102-0c67ad87649a.jpg)
2. Добавлены поля «Врач», «Специализация», «Статус» из документа «Заявка».
![2](https://user-images.githubusercontent.com/52575191/77723177-8832b180-7011-11ea-9be4-fa8ab217af7a.jpg)
3. Вид события = исходящий звонок.
![3](https://user-images.githubusercontent.com/52575191/77723178-88cb4800-7011-11ea-8f6f-d3e876e5801c.jpg)
4. Переименовано поле «Ответственный» на «Оператор» при помощи псевдонима.
![4](https://user-images.githubusercontent.com/52575191/77723179-8963de80-7011-11ea-810f-bea5b3ae1837.jpg)

**Comment by nmivan** [comment]
Чуть скорректирую. Ты засунула описание задачи в заголовок, а решение - в описание. Ты описание клади в описание, а решение потом комментом прикладывай, а то заголовок задачи нечитаемым получается.

**Comment by nmivan** [comment]
1. Под группировкой тут имеется в виду не группировка в запросе, а группировка в настройках;
2. Если добавила заявку в запрос, показывай настройку связей;

**Comment by nmivan** [comment]
А тут будешь исправлять и комментировать?

**Comment by TanyaAnferova** [comment]
Буду, но у меня эти задачи на рабочем компе, к сожалению. Или сделать по-новой?

**Comment by TanyaAnferova** [comment]
Исправляю:
1. Удалить группировка по полю Ответственный
![11 1](https://user-images.githubusercontent.com/52575191/78128882-1b178580-7430-11ea-9eda-fa6566ca0bf1.jpg)
2. Добавление полей "Врач", "Специализация", "Статус" из документа "Заявка"
![11 2](https://user-images.githubusercontent.com/52575191/78128952-36829080-7430-11ea-8ff6-b2d061547f97.jpg)
Установление связей
![11 3](https://user-images.githubusercontent.com/52575191/78129272-be689a80-7430-11ea-84fa-532eaaf42af2.jpg)

**Comment by nmivan** [comment]
Вторая связь лишняя.

**Comment by TanyaAnferova** [comment]
![11 3](https://user-images.githubusercontent.com/52575191/78134613-dee92280-7439-11ea-8d22-e5ca1d508095.jpg)

**Comment by nmivan** [comment]
Сойдет. Молодец, продолжай.
