### ISSUE TITLE
Задача 26. 

### ISSUE THREAD

**Issue by TanyaAnferova** [nmivan/learning#3]
Исходные данные: Справочник «Клиенты». 
Для роли «Администратор» сделать ограничение прав. Удалить возможность пометить на удаление элементы справочника «Клиенты». 
Оценка: 8 баллов.

**Comment by TanyaAnferova** [comment]
В разделе "Роли" для роли «Администратор» удалить возможность пометить на удаление элементы справочника «Клиенты». На вкладке "Права" выбрать справочник "Клиенты" , в колонке "Права" снять отметки на пунктах Удаление, Интерактивное удаление, Интерактивная пометка на удаление, Интерактивное снятие пометки на удаление, Интерактивное удаление помеченных
![26](https://user-images.githubusercontent.com/52575191/77725072-56701980-7016-11ea-91fb-bd2fa3601e1f.jpg)

**Comment by SimonSidoruk** [comment]
@nmivan проверь задачу

**Comment by nmivan** [comment]
Годится.
